repos:
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.8.5
  -   repo: https://github.com/life4/flakehell
      rev: v.0.7.1
      hooks:
        -   id: flakehell